{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "466c9c0a_423275a6",
        "filename": "src/button_handler_main.cpp",
        "patchSetId": 4
      },
      "lineNbr": 14,
      "author": {
        "id": 1000348
      },
      "writtenOn": "2023-05-22T03:36:19Z",
      "side": 1,
      "message": "do we not need a try catch for exceptions here?",
      "revId": "77359c396496b9eb26f56f02c0defd919400b621",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": true,
      "key": {
        "uuid": "d1e19ad8_b494cfc2",
        "filename": "src/button_handler_main.cpp",
        "patchSetId": 4
      },
      "lineNbr": 14,
      "author": {
        "id": 1000008
      },
      "writtenOn": "2023-05-22T16:16:01Z",
      "side": 1,
      "message": "I thought we were supposed to let it crash so we can get a core dump.  Looks like that\u0027s what the majority of other users are doing, though I don\u0027t really care too much either way.",
      "parentUuid": "466c9c0a_423275a6",
      "revId": "77359c396496b9eb26f56f02c0defd919400b621",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "624f3312_f7850bab",
        "filename": "src/button_handler_main.cpp",
        "patchSetId": 4
      },
      "lineNbr": 14,
      "author": {
        "id": 1000008
      },
      "writtenOn": "2023-06-29T15:31:24Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "d1e19ad8_b494cfc2",
      "revId": "77359c396496b9eb26f56f02c0defd919400b621",
      "serverId": "adbd0a64-1f21-4d83-b585-671fe73cb6e4"
    }
  ],
  "submitRequirementResults": []
}